enum EventStatus {
  UPCOMING = "UPCOMING",
  ACTIVE = "ACTIVE",
  FINISHED = "FINISHED",
  CANCELLED = "CANCELLED",
  DELETED = "DELETED",
  SETTLEMENT_DONE = "SETTLEMENT_DONE",
  WINNING_OPTION_UPDATED = "WINNING_OPTION_UPDATED",
  ABANDONED = "ABANDONED",
  NO_RESULT = "NO_RESULT",
  NOT_ENOUGH_DATA = "NOT_ENOUGH_DATA",
}

enum EventPayoutStatus {
  ONGOING = "ONGOING",
  PENDING = "PENDING",
  PROCESSING = "PROCESSING",
  COMPLETED = "COMPLETED",
  PAID = "PAID",
  FAILED = "FAILED",
  LOST = "LOST",
}

export { EventStatus, EventPayoutStatus };
